server:
  port: 8761

spring:
  application:
    name: discovery-server-atendeia

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
    prefer-ip-address: true

  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    wait-time-in-ms-when-sync-empty: 0